security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
        cp_users:
            id: App\System\Security\UserProvider
        all_users:
            chain:
                providers: [ 'users_in_memory', 'cp_users' ]
    firewalls:
        main:
            pattern: ^/api/v2
            provider: all_users
            switch_user: true
            access_token:
                token_extractors: App\System\Security\AccessTokenExtractor
                token_handler: App\System\Security\AccessTokenHandler
    access_control:
         - { path: ^/api/v2, roles: ROLE_USER }
    session_fixation_strategy: invalidate

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
