when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            environment: "%kernel.environment%"
            send_default_pii: false
            max_request_body_size: medium
            integrations:
                - Sentry\Integration\RequestIntegration
            before_send: 'sentry.callback.set_user'
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
        register_error_listener: false
        register_error_handler: false

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface
                fill_extra_context: true # Enables sending monolog context to Sentry
                process_psr_3_messages: false # Disables the resolution of PSR-3 placeholders in reported messages
